const weeks = [
{w:1,t:'Shop Numbers & Place Value',theme:'welding',skill:'Place value, whole-number operations',desc:'Read big numbers like odometer readings, engine hours, shop invoices, and part numbers.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations',problems:['A race trailer weighs 8,750 lb and the truck weighs 7,425 lb. What is the combined weight?','A shop orders 24 boxes with 36 bolts in each box. How many bolts total?','Round 48,763 to the nearest thousand.'],answers:['16,175 lb','864 bolts','49,000']},project:'Make a “garage numbers” scavenger hunt. Find and record five large numbers from vehicles, receipts, manuals, or equipment labels.'},
{w:2,t:'Lap-Time Decimals',theme:'racing',skill:'Decimal place value and operations',desc:'Use lap times and speed data to add, subtract, compare, and order decimals.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-decimals',problems:['Lap 1 is 42.68 s and Lap 2 is 41.95 s. How much faster is Lap 2?','Add 38.47 + 39.08 + 37.92.','Order from fastest to slowest: 45.12, 44.98, 45.03.'],answers:['0.73 s','115.47 s','44.98, 45.03, 45.12']},project:'Time three short runs, bike laps, or walking laps with a stopwatch. Record to hundredths if possible.'},
{w:3,t:'Fuel Fractions',theme:'racing',skill:'Fractions and mixed numbers',desc:'Model fuel tank levels, wrench sizes, and measurements with fractions.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-fractions',problems:['A 16-gallon tank is 3/4 full. How many gallons are in it?','Which is larger: 5/8 or 3/4?','A metal bar is 6 1/2 ft long. You cut off 2 3/4 ft. How much remains?'],answers:['12 gallons','3/4','3 3/4 ft']},project:'Find SAE wrench/socket sizes and put them in order from smallest to largest.'},
{w:4,t:'Cutting Metal with Fractions',theme:'welding',skill:'Add and subtract fractions',desc:'Plan cuts, leftovers, and material lengths like a fabricator.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-fractions',problems:['Cut 2 1/4 ft and 3 3/8 ft from stock. How much total?','From an 8-ft bar, remove 5 5/8 ft. What remains?','Add 7/16 + 5/16.'],answers:['5 5/8 ft','2 3/8 ft','3/4']},project:'Use scrap wood/cardboard as “steel stock.” Mark fractional cuts accurately with a tape measure.'},
{w:5,t:'Gear Ratios',theme:'dirtbike',skill:'Ratios',desc:'Understand ratios through sprockets, gears, and mechanical relationships.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic',problems:['A bike has a 13-tooth front sprocket and 52-tooth rear. Write the ratio front:rear in simplest form.','A mix uses 2 parts cleaner to 5 parts water. How much water for 6 parts cleaner?','Simplify 18:30.'],answers:['1:4','15 parts water','3:5']},project:'Count teeth on two gears/sprockets in a photo or real machine and write three equivalent ratios.'},
{w:6,t:'Speed & Unit Rates',theme:'racing',skill:'Rates and unit rates',desc:'Calculate mph, cost per part, miles per gallon, and other per-one rates.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic',problems:['A car travels 180 miles in 3 hours. What is its average speed?','12 spark plugs cost $42. What is the cost per plug?','A truck uses 8 gallons for 120 miles. Miles per gallon?'],answers:['60 mph','$3.50','15 mpg']},project:'Use a real fuel receipt or online example to calculate cost per gallon and estimated trip fuel cost.'},
{w:7,t:'Race Percentages',theme:'racing',skill:'Percent as rate per 100',desc:'Use win percentage, fuel percentage, discounts, and completion rates.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic',problems:['A racer wins 6 of 20 races. What percent?','A $80 part is 25% off. What is the discount?','75% of a 20-gallon tank equals how many gallons?'],answers:['30%','$20','15 gallons']},project:'Create a mock race season with wins and total starts. Calculate win percentages for three drivers.'},
{w:8,t:'Parts Store Math',theme:'welding',skill:'Percent, tax, discount, decimal operations',desc:'Build realistic shop invoices and compare prices.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic',problems:['A helmet is $120 with 15% off. Sale price?','Three filters cost $8.75 each. Total?','A $64 part has 8.25% sales tax. Find tax to nearest cent.'],answers:['$102','$26.25','$5.28']},project:'Build a $250 garage shopping list and stay under budget.'},
{w:9,t:'Quarter 1 Garage Challenge',theme:'racing',skill:'Review: fractions, decimals, ratios, percent',desc:'Combine the first eight weeks in one race-shop challenge.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math',problems:['A 12-gallon tank is 5/6 full. Gallons?','A 48-lap race: driver completes 75%. Laps completed?','4 tires cost $518. Unit price?'],answers:['10 gallons','36 laps','$129.50']},project:'Design a race-day budget with fuel, entry fee, parts, food, and a 10% emergency reserve.'},
{w:10,t:'Positive & Negative Temperatures',theme:'dirtbike',skill:'Negative numbers',desc:'Read below-zero temperatures and compare values on a number line.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic',problems:['Which is colder: -8°C or -3°C?','Temperature rises from -6°C to 5°C. How many degrees?','Order: 4, -7, 0, -2 from least to greatest.'],answers:['-8°C','11°C','-7, -2, 0, 4']},project:'Draw a number line styled like a temperature gauge.'},
{w:11,t:'Elevation & Trail Numbers',theme:'dirtbike',skill:'Integers and absolute value',desc:'Use trail elevations and positions above/below reference points.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic',problems:['A trail point is -18 ft relative to a ridge marker. What is its absolute value?','Compare -25 and -12. Which is greater?','Move from -8 to 14 on a number line. Distance?'],answers:['18','-12','22']},project:'Create an elevation profile of a dirt-bike trail using positive and negative values.'},
{w:12,t:'Coordinates on the Track',theme:'racing',skill:'Coordinate plane',desc:'Plot turns, pit locations, and checkpoints in all four quadrants.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic',problems:['Plot A(-3,4). Which quadrant?','What is the distance horizontally from (-5,2) to (4,2)?','Reflect (6,-2) across the y-axis.'],answers:['Quadrant II','9 units','(-6,-2)']},project:'Draw a track on coordinate paper and label at least eight points.'},
{w:13,t:'Variables in the Garage',theme:'welding',skill:'Variables and expressions',desc:'Translate shop situations into algebraic expressions.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables',problems:['Write an expression for 4 tires costing t dollars each.','Evaluate 3x+5 when x=7.','Write an expression for p dollars plus $18 shipping.'],answers:['4t','26','p+18']},project:'Label five unknown garage costs with variables, then write expressions for totals.'},
{w:14,t:'Shop Equations',theme:'welding',skill:'One-step equations',desc:'Solve for unknown costs, lengths, and quantities.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables',problems:['x + 18 = 52','5x = 65','x/4 = 9'],answers:['34','13','36']},project:'Write three equations based on real tools or parts, then solve them.'},
{w:15,t:'Formulas: Distance, Speed, Time',theme:'racing',skill:'Formulas and substitution',desc:'Use d=rt and related formulas in race situations.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables',problems:['At 50 mph for 3 hours, distance?','Travel 180 miles at 60 mph. Time?','Cover 140 miles in 2 hours. Rate?'],answers:['150 miles','3 hours','70 mph']},project:'Plan a road trip to a race and estimate travel time at two different average speeds.'},
{w:16,t:'Inequalities & Limits',theme:'dirtbike',skill:'Inequalities',desc:'Model weight limits, budgets, minimum clearances, and speed restrictions.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables',problems:['Write: load must be no more than 500 lb.','Solve x+12 < 30.','Which values satisfy x ≥ 8: 6, 8, 10?'],answers:['x ≤ 500','x < 18','8 and 10']},project:'Find five real-world limits on equipment labels and rewrite them as inequalities.'},
{w:17,t:'Area of the Shop Floor',theme:'welding',skill:'Area of rectangles, triangles, parallelograms',desc:'Measure floor space, work tables, ramps, and panels.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic',problems:['Rectangle 18 ft by 24 ft: area?','Triangle base 10 ft, height 6 ft: area?','Parallelogram base 9 in, height 4 in: area?'],answers:['432 ft²','30 ft²','36 in²']},project:'Measure a room/garage area and sketch it to scale.'},
{w:18,t:'Quarter 2 Garage Challenge',theme:'welding',skill:'Review: integers, algebra, coordinates, area',desc:'Midyear application project tying equations to a fabricated design.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math',problems:['Solve 4x=84.','Area of a 12×7 rectangle?','Distance from (-2,5) to (6,5)?'],answers:['21','84 square units','8 units']},project:'Design a welding table top using dimensions, area, cost per square foot, and a coordinate sketch.'},
{w:19,t:'Surface Area of Toolboxes',theme:'welding',skill:'Surface area',desc:'Calculate material needed to cover boxes and rectangular prisms.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic',problems:['Find SA of a 2×3×4 rectangular prism.','A cube has side 5 in. Surface area?','Which units are used for surface area?'],answers:['52 square units','150 in²','square units']},project:'Measure a small box and estimate material needed to wrap or paint all faces.'},
{w:20,t:'Volume: Fuel & Storage',theme:'racing',skill:'Volume of rectangular prisms',desc:'Use cubic units to calculate containers and storage.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic',problems:['Volume of 8×4×3 box?','A bin is 2.5 ft × 2 ft × 4 ft. Volume?','Which units measure volume?'],answers:['96 cubic units','20 ft³','cubic units']},project:'Measure a storage tote or box and calculate its volume.'},
{w:21,t:'Nets & Fabrication',theme:'welding',skill:'Nets of 3D figures',desc:'Flatten boxes into nets and connect geometry to sheet-metal fabrication.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic',problems:['How many faces does a rectangular prism have?','A cube net contains how many congruent squares?','Name three pairs of opposite faces on a box.'],answers:['6','6','top/bottom, front/back, left/right']},project:'Create a cardboard net for a small parts box, cut it out, and fold it.'},
{w:22,t:'Scale Drawings of a Garage',theme:'welding',skill:'Scale and proportional reasoning',desc:'Turn real dimensions into manageable drawings.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic',problems:['Scale 1 in = 4 ft. A 20-ft wall is how many inches on paper?','A drawing line is 6 in. Actual length at 1 in=3 ft?','At 1:12 scale, 3 inches represents how many inches actual?'],answers:['5 in','18 ft','36 in']},project:'Draw a garage or work area to scale including doors, benches, and vehicle space.'},
{w:23,t:'Dirt-Bike Jump Geometry',theme:'dirtbike',skill:'Triangles, area, geometry application',desc:'Analyze ramp profiles using triangles and measurements.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic',problems:['Ramp triangle base 12 ft, height 5 ft. Area?','Double the base with same height. What happens to area?','A rectangle 8×3 plus triangle area 6: total area?'],answers:['30 ft²','It doubles','30 square units']},project:'Sketch a safe imaginary ramp profile to scale. Do not build or ride it; this is a paper geometry project.'},
{w:24,t:'Race Data Tables',theme:'racing',skill:'Statistical questions and data tables',desc:'Collect and organize lap-time or speed data.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics',problems:['Is “What is my lap time?” statistical?','Is “What lap times did 20 racers record?” statistical?','Find range of 42, 39, 45, 41.'],answers:['No','Yes','6']},project:'Collect at least 10 timed results from a safe activity and build a data table.'},
{w:25,t:'Mean, Median & Mode',theme:'racing',skill:'Measures of center',desc:'Summarize race and shop data with mean, median, and mode.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics',problems:['Mean of 10, 12, 14?','Median of 7, 8, 9, 15, 20?','Mode of 2, 3, 3, 4, 5?'],answers:['12','9','3']},project:'Calculate mean, median, and mode for your data from Week 24.'},
{w:26,t:'Dot Plots & Histograms',theme:'racing',skill:'Data displays',desc:'Turn performance numbers into visual displays.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics',problems:['Which display shows individual values well: dot plot or histogram?','A histogram groups data into what?','What does frequency mean?'],answers:['Dot plot','intervals/bins','how often a value or group occurs']},project:'Make a dot plot or histogram from lap-time, price, or measurement data.'},
{w:27,t:'Variability in Performance',theme:'dirtbike',skill:'Range and variability',desc:'Compare consistency between riders, machines, or repeated trials.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics',problems:['Range of 18, 19, 20, 23?','Which is more consistent: set A range 2 or set B range 9?','Why can two sets have same mean but different variability?'],answers:['5','Set A','Their values can be spread differently']},project:'Compare two sets of five trial times and decide which is more consistent.'},
{w:28,t:'Tool Inventory Statistics',theme:'welding',skill:'Statistical summaries',desc:'Analyze tool sizes, prices, weights, or counts.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics',problems:['Find mean of $12, $18, $20, $30.','Find median of 4, 7, 8, 10.','Find range of 3.2, 3.9, 4.1, 5.0.'],answers:['$20','7.5','1.8']},project:'Choose 10 garage items and analyze one numerical feature such as price or weight.'},
{w:29,t:'GCF: Parts Kits',theme:'welding',skill:'Greatest common factor',desc:'Build identical kits without leftovers using common factors.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations',problems:['GCF of 18 and 24?','You have 30 bolts and 45 washers. Greatest number of identical kits?','How many bolts per kit?'],answers:['6','15 kits','2 bolts']},project:'Create a parts-kit puzzle using two or three quantities.'},
{w:30,t:'LCM: Maintenance Schedules',theme:'dirtbike',skill:'Least common multiple',desc:'Find when repeating maintenance events line up.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations',problems:['LCM of 6 and 8?','One check happens every 4 rides and another every 10 rides. When together?','LCM of 9 and 12?'],answers:['24','20 rides','36']},project:'Build a fictional maintenance schedule using three repeating intervals.'},
{w:31,t:'Distributive Property in the Shop',theme:'welding',skill:'Distributive property',desc:'Break apart calculations for faster mental math and expressions.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables',problems:['6(10+3)=?','Use distribution: 4x+12 = 4(___).','Calculate 8×27 using 8(20+7).'],answers:['78','x+3','216']},project:'Find three prices or quantities and solve using the distributive property.'},
{w:32,t:'Race Strategy Expressions',theme:'racing',skill:'Equivalent expressions',desc:'Compare different-looking expressions that represent the same total.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables',problems:['Are 3(x+4) and 3x+12 equivalent?','Simplify 5x+2x.','Evaluate 2(a+5) when a=7.'],answers:['Yes','7x','24']},project:'Write two equivalent expressions for total race cost with repeated fees.'},
{w:33,t:'Conversion Garage',theme:'welding',skill:'Unit conversion with ratios',desc:'Convert inches/feet, minutes/hours, and other familiar measurements.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic',problems:['84 inches = ? feet','2.5 hours = ? minutes','7 feet = ? inches'],answers:['7 ft','150 min','84 in']},project:'Measure five objects in inches and convert each measurement to feet and inches.'},
{w:34,t:'Trip & Trailer Planning',theme:'racing',skill:'Multi-step problem solving',desc:'Combine rates, fuel, distance, time, and budgets.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math',problems:['Trip is 240 miles at 60 mph. Driving time?','Truck gets 12 mpg. Gallons needed for 240 miles?','At $3.40/gal, fuel cost?'],answers:['4 hours','20 gallons','$68']},project:'Plan a fictional race trip including mileage, fuel, meals, and entry cost.'},
{w:35,t:'Build-a-Bike Budget',theme:'dirtbike',skill:'Review and financial application',desc:'Use decimals, percent, ratios, and equations to manage a parts budget.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math',problems:['Budget $1,200; spend $875.50. Remaining?','A $240 part is 20% off. Sale price?','Four identical parts total $156. Cost each?'],answers:['$324.50','$192','$39']},project:'Create a complete fictional build list and stay within a chosen budget.'},
{w:36,t:'Final Garage Math Championship',theme:'racing',skill:'Cumulative 6th-grade review',desc:'Finish the year with a practical capstone covering the major skills.',video:'https://www.khanacademy.org/math/cc-sixth-grade-math',problems:['3/4 of 28 laps = ?','Solve 6x=72.','Area of triangle b=14, h=6?','Mean of 40, 42, 44, 46?'],answers:['21 laps','12','42 square units','43']},project:'Create a one-page “Garage Math Championship” poster showing one example from ratios, algebra, geometry, statistics, and decimals.'}
];

const grid = document.querySelector('#weekGrid');
const dialog = document.querySelector('#weekDialog');
const dialogContent = document.querySelector('#dialogContent');
const closeBtn = document.querySelector('.close');

function label(theme){return theme==='dirtbike'?'Dirt Bikes':theme[0].toUpperCase()+theme.slice(1)}
function render(filter='all'){
  grid.innerHTML='';
  weeks.filter(x=>filter==='all'||x.theme===filter).forEach(x=>{
    const card=document.createElement('article');
    card.className='week-card';
    card.innerHTML=`<span class="week-num">WEEK ${x.w}</span><h3>${x.t}</h3><div class="tags"><span class="tag">${label(x.theme)}</span><span class="tag">${x.skill.split(',')[0]}</span></div><p>${x.desc}</p><button class="open-week" data-week="${x.w}">Open Week</button>`;
    grid.appendChild(card);
  });
}
function openWeek(num){
  const x=weeks.find(y=>y.w===num);
  dialogContent.innerHTML=`<p class="section-kicker">Week ${x.w} • ${label(x.theme)}</p><h2>${x.t}</h2><p><strong>Math focus:</strong> ${x.skill}</p><p>${x.desc}</p><div class="lesson-box"><h4>Weekly Plan</h4><p><b>Day 1:</b> Learn the concept and work examples.</p><p><b>Day 2:</b> Start the worksheet.</p><p><b>Day 3:</b> Complete the hands-on challenge.</p><p><b>Day 4:</b> Finish, check, and correct.</p></div><a class="resource-link" target="_blank" rel="noopener" href="${x.video}">Watch supporting lesson →</a><div class="worksheet"><h3>Printable Worksheet</h3><p>Name: ____________________ &nbsp; Date: __________</p><ol>${x.problems.map(p=>`<li>${p}<br><br></li>`).join('')}</ol><h4>Garage Challenge</h4><p>${x.project}</p></div><details class="answer-key"><summary><strong>Answer Key</strong></summary><ol>${x.answers.map(a=>`<li>${a}</li>`).join('')}</ol></details><button class="btn primary" onclick="window.print()">Print This Week</button>`;
  dialog.showModal();
}

grid.addEventListener('click',e=>{const b=e.target.closest('[data-week]');if(b)openWeek(Number(b.dataset.week));});
closeBtn.addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter);}));
document.querySelector('#printScope').addEventListener('click',()=>window.print());
render();
